// src/context/LanguageContext.jsx - Complete with all translations
import React, { createContext, useContext, useState, useEffect } from 'react';

// Complete translations for all 5 languages
export const translations = {
  english: {
    // Common
    appName: 'Haji Younas Contracting',
    dashboard: 'Dashboard',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    refresh: 'Refresh',
    loading: 'Loading...',
    noData: 'No Data',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    close: 'Close',
    back: 'Back',
    view: 'View',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    generate: 'Generate',
    apply: 'Apply',
    clear: 'Clear',
    all: 'All',
    none: 'None',
    welcomeBack: 'Welcome back,',
    logout: 'Logout',
    profile: 'Profile',
    help: 'Help & Support',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    viewAll: 'View All Notifications',
    searchPlaceholder: 'Search anything...',
    selectLanguage: 'Select Language',
    
    // Navigation
    home: 'Home',
    reports: 'Reports',
    inventory: 'Inventory',
    workers: 'Workers',
    sites: 'Sites',
    invoices: 'Invoices',
    qualityControl: 'Quality Control',
    cumulative: 'Cumulative',
    monthlySummary: 'Monthly Summary',
    monthlyOverhead: 'Monthly Overhead',
    dailyReport: 'Daily Report',
    analytics: 'Analytics',
    dashboard: 'Dashboard',
    projects: 'Projects',
    entries: 'Entries',
    items: 'Items',
    overheadCategories: 'Overhead Categories',
    dailyEntry: 'Daily Entry',
    advances: 'Advances',
    loans: 'Loans',
    attendance: 'Attendance',
    teams: 'Teams',
    leave: 'Leave Management',
    performance: 'Performance',
    budgetForecast: 'Budget Forecasting',
    clients: 'Clients',
    equipment: 'Equipment',
    expenses: 'Expenses',
    bom: 'Bill of Materials',
    ai: 'AI Assistant',
    settings: 'Settings',
    
    // Stats
    totalRevenue: 'Total Revenue',
    totalLabour: 'Total Labour',
    totalWages: 'Total Wages',
    netProfit: 'Net Profit',
    totalSites: 'Total Sites',
    totalWorkers: 'Total Workers',
    totalEntries: 'Total Entries',
    attendance: 'Attendance',
    activeItems: 'Active Items',
    lowStock: 'Low Stock',
    stockValue: 'Stock Value',
    pendingOrders: 'Pending Orders',
    collectionRate: 'Collection Rate',
    remainingBalance: 'Remaining Balance',
    totalAmount: 'Total Amount',
    totalInvoices: 'Total Invoices',
    overdueInvoices: 'Overdue Invoices',
    paidInvoices: 'Paid Invoices',
    
    // Forms
    name: 'Name',
    location: 'Location',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
    notes: 'Notes',
    description: 'Description',
    category: 'Category',
    unit: 'Unit',
    quantity: 'Quantity',
    price: 'Price',
    total: 'Total',
    subject: 'Subject',
    contact: 'Contact',
    clientName: 'Client Name',
    clientAddress: 'Client Address',
    invoiceDate: 'Invoice Date',
    dueDate: 'Due Date',
    subtotal: 'Subtotal',
    vat: 'VAT',
    amountInWords: 'Amount in Words',
    items: 'Items',
    unitPrice: 'Unit Price',
    invoiceNumber: 'Invoice Number',
    invoice: 'Invoice',
    cpr: 'CPR',
    crNumber: 'CR Number',
    paymentTerms: 'Payment Terms',
    rating: 'Rating',
    
    // Status
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    completed: 'Completed',
    cancelled: 'Cancelled',
    approved: 'Approved',
    rejected: 'Rejected',
    draft: 'Draft',
    sent: 'Sent',
    paid: 'Paid',
    overdue: 'Overdue',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    closed: 'Closed',
    open: 'Open',
    reported: 'Reported',
    underInvestigation: 'Under Investigation',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    
    // Actions
    addSite: 'Add Site',
    addWorker: 'Add Worker',
    addEntry: 'Add Entry',
    addInvoice: 'Add Invoice',
    generateReport: 'Generate Report',
    exportData: 'Export Data',
    importData: 'Import Data',
    printReport: 'Print Report',
    viewDetails: 'View Details',
    adjustStock: 'Adjust Stock',
    autoReorder: 'Auto-Reorder',
    processDeductions: 'Process Deductions',
    recordPayment: 'Record Payment',
    reportIssue: 'Report Issue',
    reportIncident: 'Report Incident',
    newInspection: 'New Inspection',
    addMaterial: 'Add Material',
    addSupplier: 'Add Supplier',
    purchaseOrder: 'Purchase Order',
    
    // Messages
    saveSuccess: '✅ Saved successfully!',
    saveError: '❌ Failed to save!',
    deleteConfirm: 'Are you sure you want to delete this?',
    deleteSuccess: '✅ Deleted successfully!',
    deleteError: '❌ Failed to delete!',
    noResults: 'No results found',
    pleaseWait: 'Please wait...',
    
    // Reports
    dailyReportTitle: 'Daily Work Report',
    monthlyReportTitle: 'Monthly Report',
    summaryReport: 'Summary Report',
    sitePerformance: 'Site Performance',
    workerSummary: 'Worker Summary',
    period: 'Period',
    generated: 'Generated',
    executiveSummary: 'Executive Summary',
    dailyBreakdown: 'Daily Breakdown',
    
    // Settings
    generalSettings: 'General Settings',
    dataManagement: 'Data Management',
    about: 'About',
    currency: 'Currency',
    language: 'Language',
    workingHours: 'Working Hours Per Day',
    monthlyOverhead: 'Monthly Overhead',
    version: 'Version',
    companyName: 'Company Name',
    
    // Months
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    
    // Days
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // Inventory
    materials: 'Materials',
    suppliers: 'Suppliers',
    purchaseOrders: 'Purchase Orders',
    stockMovements: 'Stock Movements',
    reorderLevel: 'Reorder Level',
    minQuantity: 'Min Quantity',
    maxQuantity: 'Max Quantity',
    warehouse: 'Warehouse',
    location: 'Location',
    
    // Cumulative
    cumulativeBalance: 'Cumulative Balance',
    finalCumulative: 'Final Cumulative',
    averageNet: 'Average Net',
    bestMonth: 'Best Month',
    worstMonth: 'Worst Month',
    
    // Quality
    qualityControl: 'Quality Control',
    inspection: 'Inspection',
    issues: 'Issues',
    safetyIncidents: 'Safety Incidents',
    severity: 'Severity',
    reportIssue: 'Report Issue',
    reportIncident: 'Report Incident',
    correctiveAction: 'Corrective Action',
    
    // Loans & Advances
    loanManagement: 'Loan Management',
    advanceManagement: 'Advance Management',
    totalLoans: 'Total Loans',
    activeLoans: 'Active Loans',
    completedLoans: 'Completed Loans',
    loanAmount: 'Loan Amount',
    interestRate: 'Interest Rate',
    tenure: 'Tenure (months)',
    monthlyInstallment: 'Monthly Installment',
    loanType: 'Loan Type',
    newLoan: 'New Loan',
    newAdvance: 'New Advance',
  },
  urdu: {
    // Common - Urdu translations
    appName: 'حاجی یونس کنٹریکٹنگ',
    dashboard: 'ڈیش بورڈ',
    settings: 'ترتیبات',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    delete: 'حذف کریں',
    edit: 'ترمیم کریں',
    add: 'شامل کریں',
    search: 'تلاش کریں',
    refresh: 'ریفریش کریں',
    loading: 'لوڈ ہو رہا ہے...',
    noData: 'کوئی ڈیٹا نہیں',
    yes: 'جی ہاں',
    no: 'نہیں',
    ok: 'ٹھیک ہے',
    close: 'بند کریں',
    back: 'واپس',
    view: 'دیکھیں',
    print: 'پرنٹ کریں',
    download: 'ڈاؤن لوڈ کریں',
    upload: 'اپ لوڈ کریں',
    export: 'ایکسپورٹ کریں',
    import: 'امپورٹ کریں',
    generate: 'تیار کریں',
    apply: 'لاگو کریں',
    clear: 'صاف کریں',
    all: 'تمام',
    none: 'کوئی نہیں',
    welcomeBack: 'خوش آمدید،',
    logout: 'لاگ آؤٹ',
    profile: 'پروفائل',
    help: 'مدد',
    notifications: 'اطلاعات',
    markAllRead: 'سب پڑھا ہوا مارک کریں',
    viewAll: 'تمام اطلاعات دیکھیں',
    searchPlaceholder: 'کچھ تلاش کریں...',
    selectLanguage: 'زبان منتخب کریں',
    
    // Navigation
    home: 'ہوم',
    reports: 'رپورٹس',
    inventory: 'انوینٹری',
    workers: 'ورکرز',
    sites: 'سائٹس',
    invoices: 'انوائسز',
    qualityControl: 'کوالٹی کنٹرول',
    cumulative: 'کمیولٹیو',
    monthlySummary: 'ماہانہ خلاصہ',
    monthlyOverhead: 'ماہانہ اوورہیڈ',
    dailyReport: 'روزانہ رپورٹ',
    analytics: 'تجزیات',
    dashboard: 'ڈیش بورڈ',
    projects: 'پروجیکٹس',
    entries: 'اندراجات',
    items: 'اشیاء',
    overheadCategories: 'اوورہیڈ کیٹیگریز',
    dailyEntry: 'روزانہ اندراج',
    advances: 'ایڈوانسز',
    loans: 'قرضے',
    attendance: 'حاضری',
    teams: 'ٹیمیں',
    leave: 'چھٹی کا انتظام',
    performance: 'کارکردگی',
    budgetForecast: 'بجٹ کی پیش گوئی',
    clients: 'کلائنٹس',
    equipment: 'سامان',
    expenses: 'اخراجات',
    bom: 'مواد کی فہرست',
    ai: 'اے آئی اسسٹنٹ',
    settings: 'ترتیبات',
    
    // Stats
    totalRevenue: 'کل آمدنی',
    totalLabour: 'کل لیبر',
    totalWages: 'کل اجرت',
    netProfit: 'خالص منافع',
    totalSites: 'کل سائٹس',
    totalWorkers: 'کل ورکرز',
    totalEntries: 'کل اندراجات',
    attendance: 'حاضری',
    activeItems: 'فعال اشیاء',
    lowStock: 'کم اسٹاک',
    stockValue: 'اسٹاک کی قیمت',
    pendingOrders: 'زیر التواء آرڈرز',
    collectionRate: 'وصولی کی شرح',
    remainingBalance: 'باقی بیلنس',
    totalAmount: 'کل رقم',
    totalInvoices: 'کل انوائسز',
    overdueInvoices: 'تاخیر شدہ انوائسز',
    paidInvoices: 'ادا شدہ انوائسز',
    
    // Forms
    name: 'نام',
    location: 'مقام',
    phone: 'فون',
    email: 'ای میل',
    address: 'پتہ',
    date: 'تاریخ',
    amount: 'رقم',
    status: 'حالت',
    notes: 'نوٹس',
    description: 'تفصیل',
    category: 'کیٹیگری',
    unit: 'یونٹ',
    quantity: 'مقدار',
    price: 'قیمت',
    total: 'کل',
    subject: 'موضوع',
    contact: 'رابطہ',
    clientName: 'کلائنٹ کا نام',
    clientAddress: 'کلائنٹ کا پتہ',
    invoiceDate: 'انوائس کی تاریخ',
    dueDate: 'آخری تاریخ',
    subtotal: 'ذیلی کل',
    vat: 'ویٹ',
    amountInWords: 'لفظوں میں رقم',
    items: 'اشیاء',
    unitPrice: 'فی یونٹ قیمت',
    invoiceNumber: 'انوائس نمبر',
    invoice: 'انوائس',
    cpr: 'سی پی آر',
    crNumber: 'سی آر نمبر',
    paymentTerms: 'ادائیگی کی شرائط',
    rating: 'درجہ بندی',
    
    // Status (Urdu)
    active: 'فعال',
    inactive: 'غیر فعال',
    pending: 'زیر التواء',
    completed: 'مکمل',
    cancelled: 'منسوخ',
    approved: 'منظور شدہ',
    rejected: 'مسترد',
    draft: 'مسودہ',
    sent: 'بھیجا گیا',
    paid: 'ادا شدہ',
    overdue: 'تاخیر شدہ',
    inProgress: 'جاری',
    resolved: 'حل شدہ',
    closed: 'بند',
    open: 'کھلا',
    reported: 'رپورٹ شدہ',
    underInvestigation: 'تحقیقات میں',
    low: 'کم',
    medium: 'درمیانہ',
    high: 'زیادہ',
    critical: 'نازک',
    
    // Actions
    addSite: 'سائٹ شامل کریں',
    addWorker: 'ورکر شامل کریں',
    addEntry: 'اندراج شامل کریں',
    addInvoice: 'انوائس شامل کریں',
    generateReport: 'رپورٹ تیار کریں',
    exportData: 'ڈیٹا ایکسپورٹ کریں',
    importData: 'ڈیٹا امپورٹ کریں',
    printReport: 'رپورٹ پرنٹ کریں',
    viewDetails: 'تفصیلات دیکھیں',
    adjustStock: 'اسٹاک ایڈجسٹ کریں',
    autoReorder: 'آٹو آرڈر',
    processDeductions: 'کٹوتیاں پروسیس کریں',
    recordPayment: 'ادائیگی ریکارڈ کریں',
    reportIssue: 'مسئلہ رپورٹ کریں',
    reportIncident: 'واقعہ رپورٹ کریں',
    newInspection: 'نیا معائنہ',
    addMaterial: 'مواد شامل کریں',
    addSupplier: 'سپلائر شامل کریں',
    purchaseOrder: 'پرس چیز آرڈر',
    
    // Messages
    saveSuccess: '✅ کامیابی سے محفوظ ہو گیا!',
    saveError: '❌ محفوظ کرنے میں ناکامی!',
    deleteConfirm: 'کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟',
    deleteSuccess: '✅ کامیابی سے حذف ہو گیا!',
    deleteError: '❌ حذف کرنے میں ناکامی!',
    noResults: 'کوئی نتیجہ نہیں ملا',
    pleaseWait: 'براہ کرم انتظار کریں...',
    
    // Reports
    dailyReportTitle: 'روزانہ رپورٹ',
    monthlyReportTitle: 'ماہانہ رپورٹ',
    summaryReport: 'خلاصہ رپورٹ',
    sitePerformance: 'سائٹ کی کارکردگی',
    workerSummary: 'ورکرز کا خلاصہ',
    period: 'مدت',
    generated: 'تیار کردہ',
    executiveSummary: 'ایگزیکٹو خلاصہ',
    dailyBreakdown: 'روزانہ تفصیل',
    
    // Settings
    generalSettings: 'عمومی ترتیبات',
    dataManagement: 'ڈیٹا مینجمنٹ',
    about: 'کے بارے میں',
    currency: 'کرنسی',
    language: 'زبان',
    workingHours: 'روزانہ کام کے اوقات',
    monthlyOverhead: 'ماہانہ اوورہیڈ',
    version: 'ورژن',
    companyName: 'کمپنی کا نام',
    
    // Months (Urdu)
    january: 'جنوری',
    february: 'فروری',
    march: 'مارچ',
    april: 'اپریل',
    may: 'مئی',
    june: 'جون',
    july: 'جولائی',
    august: 'اگست',
    september: 'ستمبر',
    october: 'اکتوبر',
    november: 'نومبر',
    december: 'دسمبر',
    
    // Days (Urdu)
    monday: 'پیر',
    tuesday: 'منگل',
    wednesday: 'بدھ',
    thursday: 'جمعرات',
    friday: 'جمعہ',
    saturday: 'ہفتہ',
    sunday: 'اتوار',
    
    // Inventory
    materials: 'مواد',
    suppliers: 'سپلائرز',
    purchaseOrders: 'پرس چیز آرڈرز',
    stockMovements: 'اسٹاک کی نقل و حرکت',
    reorderLevel: 'دوبارہ آرڈر کی سطح',
    minQuantity: 'کم سے کم مقدار',
    maxQuantity: 'زیادہ سے زیادہ مقدار',
    warehouse: 'گودام',
    location: 'مقام',
    
    // Cumulative
    cumulativeBalance: 'کمیولٹیو بیلنس',
    finalCumulative: 'آخری کمیولٹیو',
    averageNet: 'اوسط نیٹ',
    bestMonth: 'بہترین مہینہ',
    worstMonth: 'بدترین مہینہ',
    
    // Quality
    qualityControl: 'کوالٹی کنٹرول',
    inspection: 'معائنہ',
    issues: 'مسائل',
    safetyIncidents: 'سیفٹی واقعات',
    severity: 'شدت',
    reportIssue: 'مسئلہ رپورٹ کریں',
    reportIncident: 'واقعہ رپورٹ کریں',
    correctiveAction: 'اصلاحی اقدام',
    
    // Loans & Advances
    loanManagement: 'قرض کا انتظام',
    advanceManagement: 'ایڈوانس کا انتظام',
    totalLoans: 'کل قرضے',
    activeLoans: 'فعال قرضے',
    completedLoans: 'مکمل قرضے',
    loanAmount: 'قرض کی رقم',
    interestRate: 'سود کی شرح',
    tenure: 'مدت (مہینے)',
    monthlyInstallment: 'ماہانہ قسط',
    loanType: 'قرض کی قسم',
    newLoan: 'نیا قرض',
    newAdvance: 'نیا ایڈوانس',
  },
  arabic: {
    // Arabic translations - similar structure
    appName: 'حاجي يونس للمقاولات',
    dashboard: 'لوحة القيادة',
    settings: 'الإعدادات',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    yes: 'نعم',
    no: 'لا',
    ok: 'موافق',
    close: 'إغلاق',
    back: 'رجوع',
    view: 'عرض',
    print: 'طباعة',
    download: 'تحميل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    generate: 'إنشاء',
    apply: 'تطبيق',
    clear: 'مسح',
    all: 'الكل',
    none: 'لا شيء',
    welcomeBack: 'مرحباً بعودتك،',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    help: 'المساعدة',
    notifications: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    viewAll: 'عرض جميع الإشعارات',
    searchPlaceholder: 'ابحث عن أي شيء...',
    selectLanguage: 'اختر اللغة',
    
    // Navigation
    home: 'الرئيسية',
    reports: 'التقارير',
    inventory: 'المخزون',
    workers: 'العمال',
    sites: 'المواقع',
    invoices: 'الفواتير',
    qualityControl: 'مراقبة الجودة',
    cumulative: 'التراكمي',
    monthlySummary: 'الملخص الشهري',
    monthlyOverhead: 'النفقات الشهرية',
    dailyReport: 'التقرير اليومي',
    analytics: 'التحليلات',
    dashboard: 'لوحة القيادة',
    projects: 'المشاريع',
    entries: 'الإدخالات',
    items: 'العناصر',
    overheadCategories: 'فئات النفقات العامة',
    dailyEntry: 'الإدخال اليومي',
    advances: 'السلف',
    loans: 'القروض',
    attendance: 'الحضور',
    teams: 'الفرق',
    leave: 'إدارة الإجازات',
    performance: 'الأداء',
    budgetForecast: 'توقعات الميزانية',
    clients: 'العملاء',
    equipment: 'المعدات',
    expenses: 'المصروفات',
    bom: 'قائمة المواد',
    ai: 'المساعد الذكي',
    settings: 'الإعدادات',
    
    // Stats (Arabic)
    totalRevenue: 'إجمالي الإيرادات',
    totalLabour: 'إجمالي العمالة',
    totalWages: 'إجمالي الأجور',
    netProfit: 'صافي الربح',
    totalSites: 'إجمالي المواقع',
    totalWorkers: 'إجمالي العمال',
    totalEntries: 'إجمالي الإدخالات',
    attendance: 'الحضور',
    activeItems: 'العناصر النشطة',
    lowStock: 'مخزون منخفض',
    stockValue: 'قيمة المخزون',
    pendingOrders: 'الطلبات المعلقة',
    collectionRate: 'معدل التحصيل',
    remainingBalance: 'الرصيد المتبقي',
    totalAmount: 'المبلغ الإجمالي',
    totalInvoices: 'إجمالي الفواتير',
    overdueInvoices: 'الفواتير المتأخرة',
    paidInvoices: 'الفواتير المدفوعة',
    
    // Forms (Arabic)
    name: 'الاسم',
    location: 'الموقع',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    date: 'التاريخ',
    amount: 'المبلغ',
    status: 'الحالة',
    notes: 'ملاحظات',
    description: 'الوصف',
    category: 'التصنيف',
    unit: 'الوحدة',
    quantity: 'الكمية',
    price: 'السعر',
    total: 'الإجمالي',
    subject: 'الموضوع',
    contact: 'جهة الاتصال',
    clientName: 'اسم العميل',
    clientAddress: 'عنوان العميل',
    invoiceDate: 'تاريخ الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    subtotal: 'المجموع الفرعي',
    vat: 'ضريبة القيمة المضافة',
    amountInWords: 'المبلغ بالكلمات',
    items: 'العناصر',
    unitPrice: 'سعر الوحدة',
    invoiceNumber: 'رقم الفاتورة',
    invoice: 'فاتورة',
    cpr: 'رقم الهوية',
    crNumber: 'رقم السجل التجاري',
    paymentTerms: 'شروط الدفع',
    rating: 'التقييم',
    
    // Status (Arabic)
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'معلق',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    approved: 'معتمد',
    rejected: 'مرفوض',
    draft: 'مسودة',
    sent: 'مرسل',
    paid: 'مدفوع',
    overdue: 'متأخر',
    inProgress: 'قيد التنفيذ',
    resolved: 'تم الحل',
    closed: 'مغلق',
    open: 'مفتوح',
    reported: 'مبلغ عنه',
    underInvestigation: 'قيد التحقيق',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'مرتفع',
    critical: 'حرج',
    
    // Actions (Arabic)
    addSite: 'إضافة موقع',
    addWorker: 'إضافة عامل',
    addEntry: 'إضافة إدخال',
    addInvoice: 'إضافة فاتورة',
    generateReport: 'إنشاء تقرير',
    exportData: 'تصدير البيانات',
    importData: 'استيراد البيانات',
    printReport: 'طباعة التقرير',
    viewDetails: 'عرض التفاصيل',
    adjustStock: 'تعديل المخزون',
    autoReorder: 'إعادة طلب تلقائي',
    processDeductions: 'معالجة الخصومات',
    recordPayment: 'تسجيل الدفع',
    reportIssue: 'الإبلاغ عن مشكلة',
    reportIncident: 'الإبلاغ عن حادث',
    newInspection: 'تفتيش جديد',
    addMaterial: 'إضافة مادة',
    addSupplier: 'إضافة مورد',
    purchaseOrder: 'أمر شراء',
    
    // Messages (Arabic)
    saveSuccess: '✅ تم الحفظ بنجاح!',
    saveError: '❌ فشل الحفظ!',
    deleteConfirm: 'هل أنت متأكد أنك تريد حذف هذا؟',
    deleteSuccess: '✅ تم الحذف بنجاح!',
    deleteError: '❌ فشل الحذف!',
    noResults: 'لا توجد نتائج',
    pleaseWait: 'يرجى الانتظار...',
    
    // Reports (Arabic)
    dailyReportTitle: 'تقرير العمل اليومي',
    monthlyReportTitle: 'التقرير الشهري',
    summaryReport: 'تقرير ملخص',
    sitePerformance: 'أداء الموقع',
    workerSummary: 'ملخص العمال',
    period: 'الفترة',
    generated: 'تم الإنشاء',
    executiveSummary: 'الملخص التنفيذي',
    dailyBreakdown: 'التفصيل اليومي',
    
    // Settings (Arabic)
    generalSettings: 'الإعدادات العامة',
    dataManagement: 'إدارة البيانات',
    about: 'حول',
    currency: 'العملة',
    language: 'اللغة',
    workingHours: 'ساعات العمل اليومية',
    monthlyOverhead: 'النفقات الشهرية',
    version: 'الإصدار',
    companyName: 'اسم الشركة',
    
    // Months (Arabic)
    january: 'يناير',
    february: 'فبراير',
    march: 'مارس',
    april: 'أبريل',
    may: 'مايو',
    june: 'يونيو',
    july: 'يوليو',
    august: 'أغسطس',
    september: 'سبتمبر',
    october: 'أكتوبر',
    november: 'نوفمبر',
    december: 'ديسمبر',
    
    // Days (Arabic)
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    sunday: 'الأحد',
    
    // Inventory (Arabic)
    materials: 'المواد',
    suppliers: 'الموردين',
    purchaseOrders: 'أوامر الشراء',
    stockMovements: 'حركات المخزون',
    reorderLevel: 'مستوى إعادة الطلب',
    minQuantity: 'الحد الأدنى للكمية',
    maxQuantity: 'الحد الأقصى للكمية',
    warehouse: 'المستودع',
    location: 'الموقع',
    
    // Cumulative (Arabic)
    cumulativeBalance: 'الرصيد التراكمي',
    finalCumulative: 'التراكمي النهائي',
    averageNet: 'متوسط الصافي',
    bestMonth: 'أفضل شهر',
    worstMonth: 'أسوأ شهر',
    
    // Quality (Arabic)
    qualityControl: 'مراقبة الجودة',
    inspection: 'التفتيش',
    issues: 'المشاكل',
    safetyIncidents: 'حوادث السلامة',
    severity: 'الشدة',
    reportIssue: 'الإبلاغ عن مشكلة',
    reportIncident: 'الإبلاغ عن حادث',
    correctiveAction: 'الإجراء التصحيحي',
    
    // Loans & Advances (Arabic)
    loanManagement: 'إدارة القروض',
    advanceManagement: 'إدارة السلف',
    totalLoans: 'إجمالي القروض',
    activeLoans: 'القروض النشطة',
    completedLoans: 'القروض المكتملة',
    loanAmount: 'مبلغ القرض',
    interestRate: 'سعر الفائدة',
    tenure: 'المدة (شهور)',
    monthlyInstallment: 'القسط الشهري',
    loanType: 'نوع القرض',
    newLoan: 'قرض جديد',
    newAdvance: 'سلفة جديدة',
  },
  french: {
    // French translations - keeping it concise for this example
    appName: 'Haji Younas Contracting',
    dashboard: 'Tableau de bord',
    settings: 'Paramètres',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    refresh: 'Rafraîchir',
    loading: 'Chargement...',
    noData: 'Aucune donnée',
    yes: 'Oui',
    no: 'Non',
    ok: 'OK',
    close: 'Fermer',
    back: 'Retour',
    view: 'Voir',
    print: 'Imprimer',
    download: 'Télécharger',
    upload: 'Téléverser',
    export: 'Exporter',
    import: 'Importer',
    generate: 'Générer',
    apply: 'Appliquer',
    clear: 'Effacer',
    all: 'Tous',
    none: 'Aucun',
    welcomeBack: 'Bon retour,',
    logout: 'Se déconnecter',
    profile: 'Profil',
    help: 'Aide',
    notifications: 'Notifications',
    markAllRead: 'Tout marquer comme lu',
    viewAll: 'Voir toutes les notifications',
    searchPlaceholder: 'Rechercher...',
    selectLanguage: 'Choisir la langue',
    
    // Navigation
    home: 'Accueil',
    reports: 'Rapports',
    inventory: 'Inventaire',
    workers: 'Travailleurs',
    sites: 'Sites',
    invoices: 'Factures',
    qualityControl: 'Contrôle qualité',
    cumulative: 'Cumulatif',
    monthlySummary: 'Résumé mensuel',
    monthlyOverhead: 'Frais généraux mensuels',
    dailyReport: 'Rapport quotidien',
    analytics: 'Analyses',
    dashboard: 'Tableau de bord',
    projects: 'Projets',
    entries: 'Entrées',
    items: 'Articles',
    overheadCategories: 'Catégories de frais généraux',
    dailyEntry: 'Entrée quotidienne',
    advances: 'Avances',
    loans: 'Prêts',
    attendance: 'Présence',
    teams: 'Équipes',
    leave: 'Gestion des congés',
    performance: 'Performance',
    budgetForecast: 'Prévisions budgétaires',
    clients: 'Clients',
    equipment: 'Équipement',
    expenses: 'Dépenses',
    bom: 'Nomenclature',
    ai: 'Assistant IA',
    settings: 'Paramètres',
    
    // Stats (French)
    totalRevenue: 'Revenu total',
    totalLabour: 'Main-d\'œuvre totale',
    totalWages: 'Salaire total',
    netProfit: 'Bénéfice net',
    totalSites: 'Total des sites',
    totalWorkers: 'Total des travailleurs',
    totalEntries: 'Total des entrées',
    attendance: 'Présence',
    activeItems: 'Articles actifs',
    lowStock: 'Stock faible',
    stockValue: 'Valeur du stock',
    pendingOrders: 'Commandes en attente',
    collectionRate: 'Taux de recouvrement',
    remainingBalance: 'Solde restant',
    totalAmount: 'Montant total',
    totalInvoices: 'Total des factures',
    overdueInvoices: 'Factures en retard',
    paidInvoices: 'Factures payées',
    
    // Forms (French)
    name: 'Nom',
    location: 'Emplacement',
    phone: 'Téléphone',
    email: 'E-mail',
    address: 'Adresse',
    date: 'Date',
    amount: 'Montant',
    status: 'Statut',
    notes: 'Remarques',
    description: 'Description',
    category: 'Catégorie',
    unit: 'Unité',
    quantity: 'Quantité',
    price: 'Prix',
    total: 'Total',
    subject: 'Sujet',
    contact: 'Contact',
    clientName: 'Nom du client',
    clientAddress: 'Adresse du client',
    invoiceDate: 'Date de facture',
    dueDate: 'Date d\'échéance',
    subtotal: 'Sous-total',
    vat: 'TVA',
    amountInWords: 'Montant en lettres',
    items: 'Articles',
    unitPrice: 'Prix unitaire',
    invoiceNumber: 'Numéro de facture',
    invoice: 'Facture',
    cpr: 'CPR',
    crNumber: 'Numéro CR',
    paymentTerms: 'Conditions de paiement',
    rating: 'Évaluation',
    
    // Status (French)
    active: 'Actif',
    inactive: 'Inactif',
    pending: 'En attente',
    completed: 'Terminé',
    cancelled: 'Annulé',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    draft: 'Brouillon',
    sent: 'Envoyé',
    paid: 'Payé',
    overdue: 'En retard',
    inProgress: 'En cours',
    resolved: 'Résolu',
    closed: 'Fermé',
    open: 'Ouvert',
    reported: 'Signalé',
    underInvestigation: 'En cours d\'enquête',
    low: 'Faible',
    medium: 'Moyen',
    high: 'Élevé',
    critical: 'Critique',
    
    // Actions (French)
    addSite: 'Ajouter un site',
    addWorker: 'Ajouter un travailleur',
    addEntry: 'Ajouter une entrée',
    addInvoice: 'Ajouter une facture',
    generateReport: 'Générer un rapport',
    exportData: 'Exporter les données',
    importData: 'Importer les données',
    printReport: 'Imprimer le rapport',
    viewDetails: 'Voir les détails',
    adjustStock: 'Ajuster le stock',
    autoReorder: 'Réapprovisionnement automatique',
    processDeductions: 'Traiter les déductions',
    recordPayment: 'Enregistrer le paiement',
    reportIssue: 'Signaler un problème',
    reportIncident: 'Signaler un incident',
    newInspection: 'Nouvelle inspection',
    addMaterial: 'Ajouter un matériau',
    addSupplier: 'Ajouter un fournisseur',
    purchaseOrder: 'Bon de commande',
    
    // Messages (French)
    saveSuccess: '✅ Enregistré avec succès!',
    saveError: '❌ Échec de l\'enregistrement!',
    deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ceci?',
    deleteSuccess: '✅ Supprimé avec succès!',
    deleteError: '❌ Échec de la suppression!',
    noResults: 'Aucun résultat trouvé',
    pleaseWait: 'Veuillez patienter...',
    
    // Reports (French)
    dailyReportTitle: 'Rapport de travail quotidien',
    monthlyReportTitle: 'Rapport mensuel',
    summaryReport: 'Rapport sommaire',
    sitePerformance: 'Performance du site',
    workerSummary: 'Résumé des travailleurs',
    period: 'Période',
    generated: 'Généré',
    executiveSummary: 'Résumé exécutif',
    dailyBreakdown: 'Répartition quotidienne',
    
    // Settings (French)
    generalSettings: 'Paramètres généraux',
    dataManagement: 'Gestion des données',
    about: 'À propos',
    currency: 'Devise',
    language: 'Langue',
    workingHours: 'Heures de travail par jour',
    monthlyOverhead: 'Frais généraux mensuels',
    version: 'Version',
    companyName: 'Nom de l\'entreprise',
    
    // Months (French)
    january: 'Janvier',
    february: 'Février',
    march: 'Mars',
    april: 'Avril',
    may: 'Mai',
    june: 'Juin',
    july: 'Juillet',
    august: 'Août',
    september: 'Septembre',
    october: 'Octobre',
    november: 'Novembre',
    december: 'Décembre',
    
    // Days (French)
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
    
    // Inventory (French)
    materials: 'Matériaux',
    suppliers: 'Fournisseurs',
    purchaseOrders: 'Commandes d\'achat',
    stockMovements: 'Mouvements de stock',
    reorderLevel: 'Niveau de réapprovisionnement',
    minQuantity: 'Quantité minimale',
    maxQuantity: 'Quantité maximale',
    warehouse: 'Entrepôt',
    location: 'Emplacement',
    
    // Cumulative (French)
    cumulativeBalance: 'Solde cumulatif',
    finalCumulative: 'Cumulatif final',
    averageNet: 'Moyenne nette',
    bestMonth: 'Meilleur mois',
    worstMonth: 'Pire mois',
    
    // Quality (French)
    qualityControl: 'Contrôle qualité',
    inspection: 'Inspection',
    issues: 'Problèmes',
    safetyIncidents: 'Incidents de sécurité',
    severity: 'Gravité',
    reportIssue: 'Signaler un problème',
    reportIncident: 'Signaler un incident',
    correctiveAction: 'Action corrective',
    
    // Loans & Advances (French)
    loanManagement: 'Gestion des prêts',
    advanceManagement: 'Gestion des avances',
    totalLoans: 'Total des prêts',
    activeLoans: 'Prêts actifs',
    completedLoans: 'Prêts terminés',
    loanAmount: 'Montant du prêt',
    interestRate: 'Taux d\'intérêt',
    tenure: 'Durée (mois)',
    monthlyInstallment: 'Mensualité',
    loanType: 'Type de prêt',
    newLoan: 'Nouveau prêt',
    newAdvance: 'Nouvelle avance',
  },
  italian: {
    // Italian translations - keeping it concise for this example
    appName: 'Haji Younas Contracting',
    dashboard: 'Cruscotto',
    settings: 'Impostazioni',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    add: 'Aggiungi',
    search: 'Cerca',
    refresh: 'Aggiorna',
    loading: 'Caricamento...',
    noData: 'Nessun dato',
    yes: 'Sì',
    no: 'No',
    ok: 'OK',
    close: 'Chiudi',
    back: 'Indietro',
    view: 'Visualizza',
    print: 'Stampa',
    download: 'Scarica',
    upload: 'Carica',
    export: 'Esporta',
    import: 'Importa',
    generate: 'Genera',
    apply: 'Applica',
    clear: 'Cancella',
    all: 'Tutti',
    none: 'Nessuno',
    welcomeBack: 'Bentornato,',
    logout: 'Esci',
    profile: 'Profilo',
    help: 'Aiuto',
    notifications: 'Notifiche',
    markAllRead: 'Segna tutti come letti',
    viewAll: 'Visualizza tutte le notifiche',
    searchPlaceholder: 'Cerca qualsiasi cosa...',
    selectLanguage: 'Seleziona lingua',
    
    // Navigation (Italian)
    home: 'Home',
    reports: 'Rapporti',
    inventory: 'Inventario',
    workers: 'Lavoratori',
    sites: 'Siti',
    invoices: 'Fatture',
    qualityControl: 'Controllo qualità',
    cumulative: 'Cumulativo',
    monthlySummary: 'Riepilogo mensile',
    monthlyOverhead: 'Spese generali mensili',
    dailyReport: 'Rapporto giornaliero',
    analytics: 'Analisi',
    dashboard: 'Cruscotto',
    projects: 'Progetti',
    entries: 'Voci',
    items: 'Articoli',
    overheadCategories: 'Categorie di spese generali',
    dailyEntry: 'Voce giornaliera',
    advances: 'Anticipi',
    loans: 'Prestiti',
    attendance: 'Presenze',
    teams: 'Team',
    leave: 'Gestione ferie',
    performance: 'Performance',
    budgetForecast: 'Previsioni budget',
    clients: 'Clienti',
    equipment: 'Attrezzatura',
    expenses: 'Spese',
    bom: 'Distinta base',
    ai: 'Assistente AI',
    settings: 'Impostazioni',
    
    // Stats (Italian)
    totalRevenue: 'Entrate totali',
    totalLabour: 'Lavoro totale',
    totalWages: 'Salario totale',
    netProfit: 'Profitto netto',
    totalSites: 'Totale siti',
    totalWorkers: 'Totale lavoratori',
    totalEntries: 'Totale voci',
    attendance: 'Presenze',
    activeItems: 'Articoli attivi',
    lowStock: 'Scorte basse',
    stockValue: 'Valore delle scorte',
    pendingOrders: 'Ordini in sospeso',
    collectionRate: 'Tasso di riscossione',
    remainingBalance: 'Saldo residuo',
    totalAmount: 'Importo totale',
    totalInvoices: 'Totale fatture',
    overdueInvoices: 'Fatture scadute',
    paidInvoices: 'Fatture pagate',
    
    // Forms (Italian)
    name: 'Nome',
    location: 'Posizione',
    phone: 'Telefono',
    email: 'Email',
    address: 'Indirizzo',
    date: 'Data',
    amount: 'Importo',
    status: 'Stato',
    notes: 'Note',
    description: 'Descrizione',
    category: 'Categoria',
    unit: 'Unità',
    quantity: 'Quantità',
    price: 'Prezzo',
    total: 'Totale',
    subject: 'Oggetto',
    contact: 'Contatto',
    clientName: 'Nome cliente',
    clientAddress: 'Indirizzo cliente',
    invoiceDate: 'Data fattura',
    dueDate: 'Data scadenza',
    subtotal: 'Subtotale',
    vat: 'IVA',
    amountInWords: 'Importo in parole',
    items: 'Articoli',
    unitPrice: 'Prezzo unitario',
    invoiceNumber: 'Numero fattura',
    invoice: 'Fattura',
    cpr: 'CPR',
    crNumber: 'Numero CR',
    paymentTerms: 'Termini di pagamento',
    rating: 'Valutazione',
    
    // Status (Italian)
    active: 'Attivo',
    inactive: 'Inattivo',
    pending: 'In attesa',
    completed: 'Completato',
    cancelled: 'Annullato',
    approved: 'Approvato',
    rejected: 'Respinto',
    draft: 'Bozza',
    sent: 'Inviato',
    paid: 'Pagato',
    overdue: 'Scaduto',
    inProgress: 'In corso',
    resolved: 'Risolto',
    closed: 'Chiuso',
    open: 'Aperto',
    reported: 'Segnalato',
    underInvestigation: 'In indagine',
    low: 'Basso',
    medium: 'Medio',
    high: 'Alto',
    critical: 'Critico',
    
    // Actions (Italian)
    addSite: 'Aggiungi sito',
    addWorker: 'Aggiungi lavoratore',
    addEntry: 'Aggiungi voce',
    addInvoice: 'Aggiungi fattura',
    generateReport: 'Genera rapporto',
    exportData: 'Esporta dati',
    importData: 'Importa dati',
    printReport: 'Stampa rapporto',
    viewDetails: 'Visualizza dettagli',
    adjustStock: 'Regola scorte',
    autoReorder: 'Riordino automatico',
    processDeductions: 'Elabora detrazioni',
    recordPayment: 'Registra pagamento',
    reportIssue: 'Segnala problema',
    reportIncident: 'Segnala incidente',
    newInspection: 'Nuova ispezione',
    addMaterial: 'Aggiungi materiale',
    addSupplier: 'Aggiungi fornitore',
    purchaseOrder: 'Ordine di acquisto',
    
    // Messages (Italian)
    saveSuccess: '✅ Salvato con successo!',
    saveError: '❌ Errore durante il salvataggio!',
    deleteConfirm: 'Sei sicuro di voler eliminare questo?',
    deleteSuccess: '✅ Eliminato con successo!',
    deleteError: '❌ Errore durante l\'eliminazione!',
    noResults: 'Nessun risultato trovato',
    pleaseWait: 'Attendere prego...',
    
    // Reports (Italian)
    dailyReportTitle: 'Rapporto di lavoro giornaliero',
    monthlyReportTitle: 'Rapporto mensile',
    summaryReport: 'Rapporto riassuntivo',
    sitePerformance: 'Performance del sito',
    workerSummary: 'Riepilogo lavoratori',
    period: 'Periodo',
    generated: 'Generato',
    executiveSummary: 'Riepilogo esecutivo',
    dailyBreakdown: 'Ripartizione giornaliera',
    
    // Settings (Italian)
    generalSettings: 'Impostazioni generali',
    dataManagement: 'Gestione dati',
    about: 'Informazioni',
    currency: 'Valuta',
    language: 'Lingua',
    workingHours: 'Ore di lavoro al giorno',
    monthlyOverhead: 'Spese generali mensili',
    version: 'Versione',
    companyName: 'Nome dell\'azienda',
    
    // Months (Italian)
    january: 'Gennaio',
    february: 'Febbraio',
    march: 'Marzo',
    april: 'Aprile',
    may: 'Maggio',
    june: 'Giugno',
    july: 'Luglio',
    august: 'Agosto',
    september: 'Settembre',
    october: 'Ottobre',
    november: 'Novembre',
    december: 'Dicembre',
    
    // Days (Italian)
    monday: 'Lunedì',
    tuesday: 'Martedì',
    wednesday: 'Mercoledì',
    thursday: 'Giovedì',
    friday: 'Venerdì',
    saturday: 'Sabato',
    sunday: 'Domenica',
    
    // Inventory (Italian)
    materials: 'Materiali',
    suppliers: 'Fornitori',
    purchaseOrders: 'Ordini di acquisto',
    stockMovements: 'Movimenti di magazzino',
    reorderLevel: 'Livello di riordino',
    minQuantity: 'Quantità minima',
    maxQuantity: 'Quantità massima',
    warehouse: 'Magazzino',
    location: 'Posizione',
    
    // Cumulative (Italian)
    cumulativeBalance: 'Saldo cumulativo',
    finalCumulative: 'Cumulativo finale',
    averageNet: 'Media netta',
    bestMonth: 'Mese migliore',
    worstMonth: 'Peggior mese',
    
    // Quality (Italian)
    qualityControl: 'Controllo qualità',
    inspection: 'Ispezione',
    issues: 'Problemi',
    safetyIncidents: 'Incidenti di sicurezza',
    severity: 'Gravità',
    reportIssue: 'Segnala problema',
    reportIncident: 'Segnala incidente',
    correctiveAction: 'Azione correttiva',
    
    // Loans & Advances (Italian)
    loanManagement: 'Gestione prestiti',
    advanceManagement: 'Gestione anticipi',
    totalLoans: 'Totale prestiti',
    activeLoans: 'Prestiti attivi',
    completedLoans: 'Prestiti completati',
    loanAmount: 'Importo del prestito',
    interestRate: 'Tasso di interesse',
    tenure: 'Durata (mesi)',
    monthlyInstallment: 'Rate mensili',
    loanType: 'Tipo di prestito',
    newLoan: 'Nuovo prestito',
    newAdvance: 'Nuovo anticipo',
  }
};

// Get language direction
export const getLanguageDirection = (lang) => {
  const rtlLanguages = ['urdu', 'arabic'];
  return rtlLanguages.includes(lang) ? 'rtl' : 'ltr';
};

// Get language name
export const getLanguageName = (lang) => {
  const names = {
    english: 'English',
    urdu: 'اردو',
    arabic: 'العربية',
    french: 'Français',
    italian: 'Italiano'
  };
  return names[lang] || lang;
};

// Get language flag emoji
export const getLanguageFlag = (lang) => {
  const flags = {
    english: '🇬🇧',
    urdu: '🇵🇰',
    arabic: '🇸🇦',
    french: '🇫🇷',
    italian: '🇮🇹'
  };
  return flags[lang] || '🌐';
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children, initialLanguage = 'english' }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('app_language');
    if (saved && translations[saved]) {
      return saved;
    }
    return initialLanguage;
  });

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('app_language', lang);
      document.documentElement.dir = getLanguageDirection(lang);
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    document.documentElement.dir = getLanguageDirection(language);
    document.documentElement.lang = language;
  }, []);

  const value = {
    language,
    setLanguage: changeLanguage,
    t,
    getLanguageName: (lang) => getLanguageName(lang),
    getLanguageFlag: (lang) => getLanguageFlag(lang),
    isRTL: getLanguageDirection(language) === 'rtl',
    availableLanguages: Object.keys(translations)
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};